### ISSUE TITLE
Allow user to choose the date that should be used as the cohort_end_date

### ISSUE THREAD

**Issue by chrisknoll** [OHDSI/Circe#34]
Currently, each cohort expression criteria determines which field to use as the cohort end date.  For example, for condition_occurrence criteria, it uses condition_end_date.  For drug_era, it uses drug_era_end_date.  One option that was requested was to use the observation_period_end_date that was associated with the event of interest.  Another option could be to have the user provide an end date.  Still another option could be the user adds a fixed number of days to the end date.

The possibilities are endless, so we need to determine how to give the user this endless flexibility  in a webapp.

**Comment by ablack3** [comment]
Hi @chrisknoll, I have a request related to this. I see this is quite an old issue but maybe my request belongs here. 

We would like to use the index event end date as the cohort end date. Currently we can use the end of observation period or fixed days or drug discontinuation. 

The use case here is to have a cohort indexed on a hospitalization (visit_start_date) and then have the cohort_exit be the discharge date (visit_end_date). I don't think this is currently supported but let me know if it is. Otherwise are you open to adding this exit criteria to circe. The change to the SQL is quite small.

```
# I made a very small change to this sql

# -- By default, cohort exit at the event's op end date
# select event_id, person_id, op_end_date as end_date from #included_events

# was changed to

# -- Use event end date as exit date
# select event_id, person_id, end_date from #included_events

```

We have had this request come up a couple times recently.

**Comment by chrisknoll** [comment]
Just use DateAdjustment criteria:   Start with end date + 0d, end with end date + 1d.

**Comment by ablack3** [comment]
omg. so simple. haha. Thank you!!
