### ISSUE TITLE
Circe not working: empty frontpage

### ISSUE THREAD

**Issue by PRijnbeek** [OHDSI/Circe#51]
Hi all,

I am currently busy installing all the OHDSI tools. This is working out fine, WebAPI is running and all other tools are showing up fine in the browser. 

The only tool I cannot get to work is CIRCE. I see an empty page (see attachment). I checked the config.js and the webapi is set correctly (same as in the other tools). The source_daimon settings are:

INSERT INTO ohdsi.source (source_id, source_name, source_key, source_connection, source_dialect) VALUES (1, 'cdm_ipci_dopey', 'cdm_ipci_dopey', 'jdbc:postgresql://localhost:5432/CDM-IPCI-DOPEY?user=postgres&password=####', 'postgresql');

Cdm:
INSERT INTO ohdsi.source_daimon (source_daimon_id, source_id, daimon_type, table_qualifier, priority) VALUES (1,1,0, 'cdm', 0);
Vocab:
INSERT INTO ohdsi.source_daimon (source_daimon_id, source_id, daimon_type, table_qualifier, priority) VALUES (2,1,1, 'cdm', 0);
Results
INSERT INTO ohdsi.source_daimon (source_daimon_id, source_id, daimon_type, table_qualifier, priority) VALUES (3,1,2, 'cdm', 0);

All ohdsi webapi tables are in a separate schema 'ohdsi'

Any thoughts what might be the problem? 

I also tried to install via OLYMPUS and got it working there (after figuring out the the cdm, cohort and results cannot be the same schema..). However, there is no daimon_type for cohort in the instructions on the forum is this not needed when installing standalone. Could this be the problem??

Thanks

**Comment by fdefalco** [comment]
Sorry - I don't see an attachment.  Do you see any errors if you use Chrome and open the developer console (ctrl-shift-I)?  The configuration information for the daimon types is listed on the wiki here:

https://github.com/OHDSI/WebAPI/wiki/Source-Configuration

**Comment by PRijnbeek** [comment]
![circe-empty](https://cloud.githubusercontent.com/assets/7252105/12239275/3100ddbe-b888-11e5-8be5-2d6fc8e9fc44.png)

I do see unknown property name at webkit (see screen shot, that is hopefully now added).

I had seen that wiki page thanks

**Comment by fdefalco** [comment]
I can see there are two errors.  If you click the red circle with an X in it at the top right it should open the console in the bottom right of the screen which should included the errors.  If you could please also send a shot of the network tab from the developer windows.

**Comment by chrisknoll** [comment]
@PRijnbeek , There are a few pre-flight checks you can do before you go into circe.

First, you can hit these URLs to see if you get any data:
http://localhost:8080/WebAPI/source/sources
This will output all the configured sources.

Next, go to:
http://localhost:8080/WebAPI/cohortdefinition
This should return an empty array (since you haven't created any definitions yet).Most likely, this is where you're getting your error.  So let us know if you do get an error in the above url.

Note, I put localhost:8080 as the webserver for your webapi.  This is what comes as default when you pull the circe tool from git. You will need to edit the  config.js file in the /js folder to point to the right URL for the WebAPI service.

Edit: Sorry, Peter, I missed the part about you confirming the config.js was updated, etc.  So all we need to see if  the /sources and the /cohortdefinition calls complete successfully. Those are the two main calls that happen when the Circe tool starts up.  

-Chris

**Comment by PRijnbeek** [comment]
Hi Both,

Thanks for the help guys.

@fdefalco  the two errors helped I think. It looks like CIRCE is looking for another WebAPI at port 20000 which is what I think OLYMPUS is using right (see attachment). However config.js is pointing to the right webAPI? I do not understand why it still takes the other port?
![circe connection error](https://cloud.githubusercontent.com/assets/7252105/12260780/b1f81ab4-b91d-11e5-85f8-f6863b9fe255.png)

@chrisknoll both calls work fine when using this port so I think the problem is related to CIRCE for some reason not using the config.js:

define([], function () {
    var config = {};
    config.webAPIRoot = "http://localhost:8080/WebAPI/"
    return config;
});

If you want to have a look via a remote session I can arrange that later today via  a gotomeeting if that would help?

**Comment by chrisknoll** [comment]
Hi, Peter,
  Before a remote sharing,  I think the problem is just how circe is getting the config to the webapi. Thre's a file under the /circe/js folder (the root of circe / js folder) called config.js. This is the file that circe reads to get the webAPI root.  You mentioned Olympus, so I'm not sure if some custom change was made to embed CIRCE into Olympus.  If we can understand what's happening three, that should fix the issue in CIRCE.  

Which was the correct url? port 8080 or port 20000?

**Comment by PRijnbeek** [comment]
Yes i know and that file is pointing correctly to 8080 but circe is still taking 20000.

We also tried installing OLYMPUS but we decided to move to standalone because we like to be able to update etc and not all is in OLYMPUS like ATLAS.

Verstuurd vanaf mijn iPhone

Op 12 jan. 2016 om 17:30 heeft Chris Knoll <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:

Hi, Peter,
Before a remote sharing, I think the problem is just how circe is getting the config to the webapi. Thre's a file under the /circe/js folder (the root of circe / js folder) called config.js. This is the file that circe reads to get the webAPI root. You mentioned Olympus, so I'm not sure if some custom change was made to embed CIRCE into Olympus. If we can understand what's happening three, that should fix the issue in CIRCE.

Which was the correct url? port 8080 or port 20000?

**Comment by chrisknoll** [comment]
Ok, Peter, let's set up a remote share. I can host a webex and let you share your screen that way, if you like.  Can you send me a private message on forums.ohdsi.org so that I can send you the webex details, or if you want to host, you can send me the info via forums.ohdsi.org (so that we don't have this information forever stored in the github issue repository :).

-Chris

**Comment by chrisknoll** [comment]
Worked with Peter and got his local env online.
