### ISSUE TITLE
Importing invalid concept ID leads to empty row in codeset editor

### ISSUE THREAD

**Issue by vojtechhuser** [OHDSI/Circe#8]
I have a CIRCE cohort (id 58) (TSH tested people).
I am trying to specify all people who had this CPT code CPT-4 84443. 
It is CDMV ConceptID (=CID) of 2212593.

How I define a code set consisting of one code and simply type the code. 

Because I am not able to find it due to so many domains and it is not found in any of them.

![2015-04-15 11_02_51-achilles](https://cloud.githubusercontent.com/assets/7526119/7162002/357db13a-e360-11e4-8c1b-1b39944dc1d8.png)

**Comment by chrisknoll** [comment]
Hi.
  To do this, go into your CIRCE definition, create a new codeset, call it Thyroid Stimulating Hormone.  To quickly pull in the concept, click the 'import' button, and paste the concept id '2212593' (the initial textbox is small, sorry!).  Click the done button and you should see a concept show up in the table with 3 checkboxes. Since you just want this exact concept, you don't need descendants (and I don't think we have hierarchys of CPT4 codes, but you could try it!)

Then go to your Expression tab in CIRCE, and add a new procedure filter.  The dropdown that says 'Any Procedure', select your concept set 'Thyroid Stimulating Hormone'.  Add any other filters you might want (like start window, only first occurrence, etc).

Click ShowSQL and you'll have template sql taht you will need to replace with your environment values.  If you are running this on your own local install of webAPI (and you have it configured to a valid CDM) you can click Generate right in circe, and the ohdsi_schema.cohort table will contain the results.

-Chris

**Comment by vojtechhuser** [comment]
so I am able to see a tiny textbox but for some reason the concepts don't show

See the problem below
![2015-04-15 17_04_47-www ohdsi org_web_circe_](https://cloud.githubusercontent.com/assets/7526119/7169230/937dbaba-e391-11e4-851d-c18573fb36a6.png)

**Comment by chrisknoll** [comment]
Not sure what you are doing on your side, but i did notice that if i give it an invalid concept ID, it reports an error and inserts a empty row. I need to handle this case. However, I went to hermes: http://www.ohdsi.org/web/hermes/#/concept/2212593, and that concept does not exist. Where did this concept come from?

I've updated your try2 concept set with a code that was found in the vocab.

**Comment by ericaVoss** [comment]
This concept exists in the 03-APR-15 Vocab.

``` txt
CONCEPT_ID = 2212593
CONCEPT_NAME = Blood test, thyroid stimulating hormone (TSH)
DOMAIN = Measurement
VOCAB ID = CPT4
```

Is CPT4 considered a restricted vocab?

**Comment by chrisknoll** [comment]
No, most likely our public website isn't up to the latest vocab.  

@leeevans, can you get the latest vocab put into our public api?

**Comment by ericaVoss** [comment]
It is up-to-date - you can see the version when you hit the gear near the search bar.

**Comment by pbr6cornell** [comment]
Cpt4 is a restricted vocabulary and not available on the public webapi.

**Comment by chrisknoll** [comment]
I've renamed this issue to reflect the actual problem.

**Comment by vojtechhuser** [comment]
thank you for all the responses. One suggestion would be to somehow show that the concept is valid (in larger sense) and just "restricted" and show the vocabulary (CPT4).

I like the public CIRCE instance - it can give me SQL code, but if I can't use restricted code. It makes the public instance unusable for my purposes.

Also, allowing restricted vocabularies to be used in any CIRCE instance would also be good. Since we are only dealing with CDMV Concept IDs. But I can see the reasons for the current decision as well.
